config/routes.rb
Rails.application.routes.draw do

  root to: "tracks#index"
  get "/my_tracks" => "tracks#my_tracks"
  put "/save_track" => "tracks#save_track"
  delete "/remove_track" => "tracks#remove_track"
  get "/index" => "tracks#index"
  get "auth/spotify" => "authentications#create"
  get "auth/callback" => "authentications#callback"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

  def create
    client_id = "ef0a52e548f94683814292d0012d0211"
    response_type = "code"
    redirect_uri = "http://52.34.218.67:3000/auth/callback"
    the_scope = "user-library-read user-library-modify"
    redirect_to("https://accounts.spotify.com/authorize" + "?client_id=" + client_id + "&response_type=" + response_type + "&redirect_uri=" + redirect_uri + "&scope=" + the_scope)
  end

  def callback
    spotify_auth_code = params[:code]

    request = Typhoeus::Request.new(
    URI.escape("https://accounts.spotify.com/api/token"),
    method: :post,
    params: { grant_type: "authorization_code", code: spotify_auth_code, redirect_uri: "http://52.34.218.67:3000/auth/callback", client_id: "ef0a52e548f94683814292d0012d0211", client_secret: "40230093580a491abb79c3260257663b" })

    request.run
    response = JSON.parse(request.response.body)

    session[:spotify_access_token] = response["access_token"]
    session[:spotify_token_type] = response["token_type"]

    redirect_to root_path
  end



end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index
    if params[:search]
      search = Typhoeus::Request.new("https://api.spotify.com/v1/search", method: :get, params: {q: params[:search], type: "track"})
      search.run
      results = search.response.body
      results = JSON.parse(results)
      items = results["tracks"]["items"]
      @results = []
      items.each do |item|
        track_id = item["id"]
        title = item["name"]
        artist = item["artists"].first["name"]
        album = item["album"]["name"]
        preview_url = item["preview_url"]
        href = item["href"]
        if item["album"]["images"].first
          image_url = item["album"]["images"].first["url"]
        else
          image_url = "http://4.bp.blogspot.com/_CHG2GRbeET8/SS3f-tcSNiI/AAAAAAAAJEk/qVdRYu1MLMs/s1600/missing-715826.gif"
        end
        @results << {:track_id => track_id, :title => title, :artist => artist, :album => album, :image_url => image_url, :preview_url => preview_url, :href => href }
      end
    end
  render "index"
  end

  def my_tracks
    request = Typhoeus::Request.new(
    URI.escape("https://api.spotify.com/v1/me/tracks"),
    method: :get,
    params: {},
    headers: { "Authorization": session[:spotify_token_type] + " " + session[:spotify_access_token] })
    request.run
    response = JSON.parse(request.response.body)
    response = response["items"]
    @tracks = []
    response.each do |item|
      item = item["track"]
      track_id = item["id"]
      title = item["name"]
      artist = item["artists"].first["name"]
      album = item["album"]["name"]
      preview_url = item["preview_url"]
      href = item["href"]
      if item["album"]["images"].first
        image_url = item["album"]["images"].first["url"]
      else
        image_url = "http://4.bp.blogspot.com/_CHG2GRbeET8/SS3f-tcSNiI/AAAAAAAAJEk/qVdRYu1MLMs/s1600/missing-715826.gif"
      end
    @tracks << {:track_id => track_id, :title => title, :artist => artist, :album => album, :image_url => image_url, :preview_url => preview_url, :href => href }
    end

    render "saved"
  end

  def save_track
    track_id = params[:track_id]
    request = Typhoeus::Request.new(
      URI.escape("https://api.spotify.com/v1/me/tracks"),
      method: :put,
      params: { ids: track_id },
      headers: { "Authorization": session[:spotify_token_type] + " " + session[:spotify_access_token] })
    request.run
    redirect_to my_tracks_path
  end

  def remove_track
    track_id = params[:track_id]
    request = Typhoeus::Request.new(
      URI.escape("https://api.spotify.com/v1/me/tracks"),
      method: :delete,
      params: { ids: track_id },
      headers: { "Authorization": session[:spotify_token_type] + " " + session[:spotify_access_token] })
    request.run
    redirect_to my_tracks_path
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Spotify API Player</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container margin-top-20">
	<div class="pull-right">
		<%= link_to "Login to Spotify", auth_spotify_path, class: "btn btn-info" %>
		<% if session[:spotify_access_token] %><%= link_to "My Saved Tracks", my_tracks_path, class: "btn btn-warning" %><% end %>
	</div>
</div>


<%= yield %>

</body>
</html>

app/views/tracks/index.html.erb
<div class="container margin-top-20">
	<div class="clearfix"></div>

<% flash.each do |key,value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

	<!--Search Form-->
	<div class="row margin-top-20">
		<%= form_tag(index_path, method: :get) do %>
			<div class="col-sm-10">
				<input type="text" name="search" class="form-control" placeholder="Search for Songs!" />
				<!-- This affects the URL bar because it is a get request. that's just magic. -->
			</div>
			<div class="col-sm-2">
				<button type="submit" class="btn btn-primary btn-block">Search Songs</button>
			</div>
		<% end %>
	</div>
	<!--/Search Form-->


	<div id="song-container">
	<% if @results %>
    <% @results.each do |track| %>
  		<!--One Song-->
  		<div class="row margin-top-20 one-song">
  			<div class="col-sm-3">
  				<img src="<%= track[:image_url] %>" class="img-responsive" />
  			</div>
  			<div class="col-sm-9">
  				<h2><%= track[:title] %></h2>
  				<p>
  					By <%= track[:artist] %>
  				</p>
  				<p>
  					Album: <%= track[:album] %>
  				</p>
  				<div class="margin-top-20">
  					<audio controls>
  						<source src="<%= track[:preview_url] %>" type="audio/mpeg">
  					</audio>
  				</div>
  				<% if session[:spotify_access_token] %>
  				<%= track[:track_id] %>
  				<div class="margin-top-20">
  					<button type="submit" class="btn btn-success btn-sm">
  						<span class="glyphicon glyphicon-ok margin-right-5"></span>
  						<%= link_to "Save Track", save_track_path(track_id: track[:track_id]), method: "PUT" %>
  					</button>
  				</div>
  				<% end %>
  			</div>
  		</div>
  		<!--/One Song-->
      <% end %>
    <% end %>
  	</div>


</div>

app/views/tracks/saved.html.erb
<div class="container margin-top-20">
	<div>
		<a href="<%= index_path %>" class="btn btn-info">
			<span class="glyphicon glyphicon-menu-left"></span>
			Back
		</a>
	</div>

	<div id="song-container">
    <% @tracks.each do |track| %>
		<!--One Song-->
		<div class="row margin-top-20 one-song">
			<div class="col-sm-3">
				<img src="<%= track[:image_url] %>" class="img-responsive" />
			</div>
			<div class="col-sm-9">
				<h2><%= track[:title]%></h2>
				<p>
					By <%= track[:artist] %>
				</p>
				<p>
					Album: <%= track[:album] %>
				</p>
				<div class="margin-top-20">
					<audio controls>
						<source src="<%= track[:preview_url] %>" type="audio/mpeg">
					</audio>
				</div>
				<%= track[:track_id] %>
				<% if session[:spotify_access_token] %>
				<div class="margin-top-20">
					<button type="submit" class="btn btn-danger btn-sm">
						<span class="glyphicon glyphicon-remove margin-right-5"></span>
						<%= link_to "Remove Track", remove_track_path(track_id: track[:track_id]), method: "DELETE" %>
					</button>
				</div>
				<% end %>
			</div>
		</div>
		<!--/One Song-->
		<% end %>
	</div>
</div>

app/views/tracks/testing.html.erb
<h1>
Hi


</h1>